baseURL = "https://www.hardwario.com"
homeURL = "/"
DefaultContentLanguage = "en"
pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  menuNames = ["main","footer","secondary"]
  homeURL = "/"
  shopURL = "https://shop.hardwario.com/"
  productionURL = "https://www.hardwario.com"

[languages]
  [languages.en]
    LanguageName = "English"
    weight = 1
    [languages.en.params]
      baseURL = "/"
  [languages.cs]
    LanguageName = "Česky"
    weight = 2
    [languages.cs.params]
      baseURL = "/cs/"
      homeURL = "/cs/"


[[languages.en.menu.footer]]
  url    = "https://developers.bigclown.com"
  name   = "Documentation"
  weight = 0

[[languages.cs.menu.footer]]
  url    = "https://developers.bigclown.com"
  name   = "Dokumentace"
  weight = 0

[[languages.en.menu.footer]]
  url    = "https://github.com/bigclownlabs"
  name   = "GitHub"
  weight = 500

[[languages.cs.menu.footer]]
  url    = "https://github.com/bigclownlabs"
  name   = "GitHub"
  weight = 800

[[languages.en.menu.footer]]
  url    = "https://shop.hardwario.com"
  name   = "Shop"
  weight = 500

[[languages.cs.menu.footer]]
  url    = "https://obchod.hardwario.cz"
  name   = "Obchod"
  weight = 500

[[languages.en.menu.secondary]]
  url    = "https://shop.hardwario.com"
  name   = "Shop"
  weight = 500

[[languages.cs.menu.secondary]]
  url    = "https://obchod.hardwario.cz"
  name   = "Obchod"
  weight = 500

[blackfriday]
smartypants = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags"
  category= "categories"

[outputs]
        home = [ "HTML", "JSON"]
        page = [ "HTML"]
