[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src https://*; child-src 'none';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
