[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'strict-dynamic' https:;script-src 'strict-dynamic'"
    X-Frame-Options = "ALLOW-FROM https://app.hubspot.com"
